### ISSUE TITLE
broken urls in README

### ISSUE THREAD

**Issue by m-tosch** [bogdanvuk/pygears#16]
I'm just getting started with pygears. Noticed that some links in the README are broken.

images/echo.png
images/echo_plot.png
images/echo_vcd.png

**Comment by ssredojevic** [comment]
Hey @m-tosch we are currently working on solving this problem. A few days ago we launched a new website on pygears.org and moved the old website (which is documentation oriented) to the doc.pygears.org domain. Therefore some paths are now broken since the path is changed.

Until than I'm sending you working version of current website here.
To open it go to: `_build/html/index.html`

We are preparing update that will close this issue but also: https://github.com/bogdanvuk/pygears/issues/14

FILE: [_build.zip](https://github.com/bogdanvuk/pygears/files/8302861/_build.zip)

**Comment by m-tosch** [comment]
Much appreciated!
